poll/urls.py
from django.urls import path

from . import views

app_name = "poll"
urlpatterns = [
    path('', views.index, name='index'),
    # ex: /polls/5/
    path('detail', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('results', views.results, name='results'),

]

polls/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('poll/', include('poll.urls'))
]

poll/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    choice_text = models.CharField(max_length=200, default = " ")
    choice_text2 = models.CharField(max_length=200, default = " ")
    def __str__(self):
        return self.question_text

    # class Choice(models.Model):
    #     # question = models.ForeignKey(Question, on_delete=models.CASCADE)
    #     choice_text = models.CharField(max_length=200)
    #     choice_text2 = models.CharField(max_length=200, default = " ")
    #     votes = models.IntegerField(default=0)
    #     def __str__(self):
    #         return self.choice_text
    #         return self.choice_text2

poll/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponse
from .models import Question
# from .models import Choice

# Create your views here.
def index(request):
    return render(request, "poll/index.html")

def detail(request):
    # return HttpResponse("You're looking at question %s." % question_id)

    context = {
        "question" : Question.objects.all()
        # "choice" : Choice.objects.all()
    }

    return render(request, "poll/detail.html", context)
   



def results(request):
    
    return render(request, "poll/results.html")

# def vote(request,):
#     # return HttpResponse("You're voting on question %s." % question_id)  
#     return render(request, "poll/vote.html")  

poll/templates/poll/detail.html
{% extends "poll/layout.html" %}


    {% block body %}

        <form action="{% url 'poll:results'%}" method="post">
        {% csrf_token %}

        <div class="quiz_q">
            {% for q in question  %}
            <h3>{{ q.question_text}}</h3>
                <div>
                
                <input type="checkbox">
                <label >{{q.choice_text}} </label><br>
                <input type="checkbox" >
                <label>{{q.choice_text2}}</label><br>
                </div>
                
            {% endfor %}

        </div>    
        <br><input type="submit" value="Vote">
        </form>  

            



             
        
       

    {% endblock %}

poll/templates/poll/index.html
{% extends "poll/layout.html" %}


    {% block body %}
        <h1>Introductory statement</h1>
        
        <div class="sp1">
            <p>Welcome to this project created mainly by Django.<br>
            This will be a simple poll<br>
            created to observe the various philosophical ideals<br>
            of people.
            I hope you enjoy this poll </p>
        </div>

        <a href="{% url 'poll:detail' %}" target = "_blank">Click here to begin</a>

    {% endblock %}

poll/templates/poll/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Poll</title>
    </head>
    <body> 
    <div class="intro">
    
    <h1>Welcome to my poll!</h1>
    
    </div>
    <div class="body">    
        {% block body %}
        {% endblock %}
    </div>

    </body>

poll/templates/poll/results.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Poll</title>
    </head>
    <body> 
    <div class="result">
    
    <p>Thank you for particiating in the poll.</p>
    <a href="{% url 'poll:detail' %}">Click here to start the poll again</a>
    
    </div>
   

    </body>